### ISSUE TITLE
Hale variables not converted correctly

### ISSUE THREAD

**Issue by kl** [geosolutions-it/hale-appschema-plugin#20]
I have the following Hale mapping that works in Hale:
```{{project:projectNamespace}}/DamOrWeir_{gid}```

When this is converted to the app-schema format I get:
```
<AttributeMapping>
  <targetAttribute>gml:identifier</targetAttribute>
    <sourceExpression>
      <OCQL>strConcat(strConcat({project:projectNamespace, '}/DamOrWeir_'), gid)</OCQL>
    </sourceExpression>
    <ClientProperty>
      <name>codeSpace</name>
      <value>strConcat({project:euID, '}')</value>
    </ClientProperty>
</AttributeMapping>
```

And then I get this error when I try to upload it to Geoserver:

```
Caused by: java.io.IOException: org.geotools.data.DataSourceException: Error parsing CQL expression strConcat(strConcat({project:projectNamespace, '}/DamOrWeir_'), gid):
Lexical error at line 1, column 21.  Encountered: "{" (123), after : "" Parsing : strConcat(strConcat({project:projectNamespace, '}/DamOrWeir_'), gid).
        at org.geotools.data.complex.config.AppSchemaDataAccessConfigurator.createFeatureTypeMappings(AppSchemaDataAccessConfigurator.java:397)
        at org.geotools.data.complex.config.AppSchemaDataAccessConfigurator.buildMappings(AppSchemaDataAccessConfigurator.java:279)
        at org.geotools.data.complex.config.AppSchemaDataAccessConfigurator.buildMappings(AppSchemaDataAccessConfigurator.java:256)
        at org.geotools.data.complex.AppSchemaDataAccessFactory.createDataStore(AppSchemaDataAccessFactory.java:115)
        at org.geotools.data.complex.AppSchemaDataAccessFactory.createDataStore(AppSchemaDataAccessFactory.java:77)
        at org.vfny.geoserver.util.DataStoreUtils.getDataAccess(DataStoreUtils.java:57)
        at org.geoserver.catalog.ResourcePool.getDataStore(ResourcePool.java:631)
        at org.geoserver.catalog.impl.DataStoreInfoImpl.getDataStore(DataStoreInfoImpl.java:33)
        at org.geoserver.rest.catalog.DataStoreFileController.dataStorePut(DataStoreFileController.java:374)
        ... 108 more
```

Does the plugin not support Hale project variables?

**Comment by nmco** [comment]
Hale project variables are currently not supported by this plug-in. A pull request implementing this functionality would be welcome :smile:, you may also consider contacting [GeoSolutions commercial support](https://www.geosolutionsgroup.com/contacts/) if you wish to fund this functionality.
